### ISSUE TITLE
Final boss errors

### ISSUE THREAD

**Issue by Drake53** [Frotty/ForestDef#20]
[Screenshots](https://imgur.com/a/61n3Sj4)
(first image didn't happen during final boss I know)
These occured on latest version (0.20r)
Side effect of these errors appears to be that certain tower projectiles move slower (as in, they don't update every tick), which happened for at least wave and artillery (with the R ability) towers.

**Comment by Frotty** [comment]
Yea thanks, the version on hive isn't latest, but end boss is generally buggy. Hoped to be reworked soon!
